#!/usr/bin/env bash

groupadd -f minetools
# Correção de permissões da pasta /opt/backup-server-bedrock
chgrp -R minetools /opt/backup-server-bedrock /opt/backup-server-java/

# Criação do arquivo de log
chgrp minetools /var/log/bedrock-backup.log /var/log/bedrock-update.log
chmod 771 /var/log/bedrock-backup.log /var/log/bedrock-update.log
chmod 711 /usr/bin/mine-server-tools /usr/bin/bedrock-tools/tools/backup-server

#exit 0

exit 0
