#!/usr/bin/env bash

groupadd -f minetools

# Permissões das pasta de Backups
chgrp -R minetools /var/mine-backups/backup-server-bedrock/ /var/mine-backups/backup-server-java/

chgrp minetools /var/log/bedrock-backup.log /var/log/bedrock-update.log /var/log/java-server.log
chgrp minetools /etc/mineservertools/bedrock-server.conf /etc/mineservertools/java-edition-server.conf
chmod 771 /var/log/bedrock-backup.log /var/log/bedrock-update.log /etc/mineservertools/bedrock-server.conf /etc/mineservertools/java-edition-server.conf
chmod 711 /usr/bin/mine-server-tools /usr/bin/bedrock-tools/tools/backup-bedrock /usr/bin/bedrock-tools/tools/bedrock-update /usr/bin/bedrock-tools/tools/download-server

dependencies=(tar wget rsync tmux pv zstd)

check_and_install() {
    echo "Verificando dependências..."
    for dep in "${dependencies[@]}"; do
        if ! dpkg -l | grep -q "$dep"; then
            echo "$dep não está instalado. Instalando..."
            sudo apt install "$dep" -y
        else
            echo "$dep já está instalado."
        fi
    done
}

add_paths_to_bashrc() {
    local user_home=$1
    local bashrc_path="$user_home/.bashrc"
    local path_entry_bedrock="export PATH=\$PATH:/usr/bin/bedrock-tools/tools"
    local path_entry_java="export PATH=\$PATH:/usr/bin/java-tools"

    if ! grep -q "$path_entry_bedrock" "$bashrc_path"; then
        echo -e "\n# PATH do MineServerTools" >> "$bashrc_path"
        echo "$path_entry_bedrock" >> "$bashrc_path"
    fi

    if ! grep -q "$path_entry_java" "$bashrc_path"; then
        echo "$path_entry_java" >> "$bashrc_path"
    fi
}

for user_home in /home/*; do
    if [ -d "$user_home" ]; then
        add_paths_to_bashrc "$user_home"
    fi
done

add_paths_to_bashrc "/root"
check_and_install
echo "Configuração finalizada."
clear
echo "Instalação do Mineservertools finalizada"

exit 0