name: Tagged release

on:
  push:
    tags:
      - "v*"
      
permissions:
  contents: "write"
  packages: "write"
  pull-requests: "read"

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v3
    
    - name: Create package
      run: make package-deb

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.DEPLOY }}"
        prerelease: false
        files: |
          dist/*.deb
